name: StatusPulse CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # Checkout Code
      # -------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # -------------------------
      # Setup Python
      # -------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: pip install ruff

      - name: Lint Code
        run: ruff check app/

      # -------------------------
      # Hadolint Scan
      # -------------------------
      - name: Hadolint Scan
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

      # -------------------------
      # BUILD DOCKER IMAGE
      # -------------------------
      - name: Build Docker Image
        run: docker build -t statuspulse-app:latest .

      # -------------------------
      # SECURITY SCAN (TRIVY - OPTIMIZED, NO INSTALL)
      # -------------------------
      - name: Trivy Image Scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest \
            image statuspulse-app:latest || true

      # -------------------------
      # START FULL STACK
      # -------------------------
      - name: Start Docker Compose Stack
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          docker compose down -v || true
          DB_PASSWORD=$DB_PASSWORD docker compose up -d --build

      # -------------------------
      # WAIT FOR SERVICES
      # -------------------------
      - name: Wait for services
        run: sleep 20

      # -------------------------
      # INSTALL TOOLS
      # -------------------------
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # -------------------------
      # RUN INTEGRATION TESTS
      # -------------------------
      - name: Run Integration Tests
        run: |
          chmod +x tests/test_integration.sh
          ./tests/test_integration.sh

      # -------------------------
      # COLLECT LOGS (ALWAYS)
      # -------------------------
      - name: Collect Logs
        if: always()
        run: docker compose logs > logs.txt

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: logs.txt
